Repository HUFS-EZport/Server, pull requests merged in 2024-02, with the labels that each got.

#22 Feature/19-이메일 인증 관련 로직
  build.gradle
  src/main/java/com/example/ezports/domain/member/controller/EmailController.java
  src/main/java/com/example/ezports/domain/member/controller/MemberController.java
  src/main/java/com/example/ezports/domain/member/entity/EmailCode.java
  src/main/java/com/example/ezports/domain/member/repository/EmailCodeRepository.java
  src/main/java/com/example/ezports/domain/member/service/EmailService.java
  src/main/java/com/example/ezports/global/config/EmailConfig.java
  src/main/java/com/example/ezports/global/config/RedisUtil.java
  src/main/java/com/example/ezports/global/email/EmailService.java
  src/main/java/com/example/ezports/global/email/dto/EmailRequestDTO.java
  src/main/java/com/example/ezports/global/exception/GlobalErrorCode.java
Labels: feature

#21 Feature/20-API repository 통합
  .github/workflows/notify-api-repo.yml
Labels: feature

#28 [CHORE]: 빌드버전 명시
  build.gradle
Labels: feature

#31 Fix/29
  src/main/java/com/example/ezports/domain/mapping/converter/ParticipantConverter.java
  src/main/java/com/example/ezports/domain/mapping/repository/ParticipantRepository.java
  src/main/java/com/example/ezports/domain/mapping/service/ParticipantService.java
  src/main/java/com/example/ezports/domain/match/converter/MatchConverter.java
  src/main/java/com/example/ezports/domain/match/dto/MatchRequestDTO.java
  src/main/java/com/example/ezports/domain/match/dto/MatchResponseDTO.java
  src/main/java/com/example/ezports/domain/match/entity/Match.java
  src/main/java/com/example/ezports/domain/team/converter/TeamConverter.java
  src/main/java/com/example/ezports/domain/team/dto/TeamRequestDTO.java
  src/main/java/com/example/ezports/domain/team/dto/TeamResponseDTO.java
  src/main/java/com/example/ezports/domain/team/entity/Team.java
  src/main/java/com/example/ezports/domain/team/service/TeamService.java
Labels: refactor

#32 Feature/30-Docker-support
  .gitignore
  Dockerfile
  docker-compose.yml
  docker/clear-image.bat
  docker/clear-image.sh
  docker/cp-jar.sh
  run-by-docker.bat
  run-by-docker.sh
Labels: feature

#33 Feature/30-Docker-support
  .gitignore
  Dockerfile
  docker-compose.yml
  docker/clear-image.bat
  docker/clear-image.sh
  docker/cp-jar.sh
  run-by-docker.bat
  run-by-docker.sh
Labels: feature

#34 [FEAT]: 응답 수정 및 MySQL 연결
  build.gradle
  src/main/java/com/example/ezports/domain/mapping/converter/ParticipantConverter.java
  src/main/java/com/example/ezports/domain/mapping/repository/ParticipantRepository.java
  src/main/java/com/example/ezports/domain/mapping/service/ParticipantService.java
  src/main/java/com/example/ezports/domain/match/converter/MatchConverter.java
  src/main/java/com/example/ezports/domain/match/dto/MatchRequestDTO.java
  src/main/java/com/example/ezports/domain/match/dto/MatchResponseDTO.java
  src/main/java/com/example/ezports/domain/match/entity/Match.java
  src/main/java/com/example/ezports/domain/team/converter/TeamConverter.java
  src/main/java/com/example/ezports/domain/team/dto/TeamRequestDTO.java
  src/main/java/com/example/ezports/domain/team/dto/TeamResponseDTO.java
  src/main/java/com/example/ezports/domain/team/entity/Team.java
  src/main/java/com/example/ezports/domain/team/service/TeamService.java
  src/main/resources/application.yml
Labels: feature

#37 Fix/36
  Dockerfile
  docker-compose.yml
Labels: refactor

#38 Fix/36
  Dockerfile
  docker-compose.yml
Labels: refactor

#40 Feature/39-테스트-서버-배포-자동화
  .github/workflows/publish-test-server.yml
Labels: feature

#42 [FEAT]: 로그인 기능 구현
  build.gradle
  src/main/java/com/example/ezports/domain/member/auth/UserDetailsServiceImpl.java
  src/main/java/com/example/ezports/domain/member/auth/utils/MemberUtils.java
  src/main/java/com/example/ezports/domain/member/auth/utils/SecurityUtils.java
  src/main/java/com/example/ezports/domain/member/controller/MemberController.java
  src/main/java/com/example/ezports/domain/member/converter/MemberConverter.java
  src/main/java/com/example/ezports/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/ezports/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/ezports/domain/member/entity/MemberRole.java
  src/main/java/com/example/ezports/domain/member/repository/MemberRepository.java
  src/main/java/com/example/ezports/domain/member/service/MemberQueryService.java
  src/main/java/com/example/ezports/domain/member/service/MemberService.java
  src/main/java/com/example/ezports/global/config/ConfigurationPropertiesConfig.java
  src/main/java/com/example/ezports/global/config/SecurityConfig.java
  src/main/java/com/example/ezports/global/consts/EzportsStatic.java
  src/main/java/com/example/ezports/global/exception/GlobalErrorCode.java
  src/main/java/com/example/ezports/global/jwt/JwtFilter.java
  src/main/java/com/example/ezports/global/jwt/JwtProperties.java
  src/main/java/com/example/ezports/global/jwt/JwtTokenService.java
  src/main/java/com/example/ezports/global/jwt/dto/AccessTokenInfo.java
  src/main/resources/application.yml
Labels: feature

#41 Feature/39 테스트-서버-배포-자동화
  .github/workflows/notify-api-repo.yml
  .github/workflows/publish-test-server.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  docker/clear-image.bat
  docker/clear-image.sh
  docker/cp-jar.sh
  run-by-docker.bat
  run-by-docker.sh
Labels: feature

#44 Fix/43-DB 사용자 이름 저장 방식 변경
  src/main/resources/application.yml
Labels: refactor

#46 [FIX]: Test server deploying
  .github/workflows/publish-test-server.yml
  docker-compose.yml
  run-by-docker.bat
  run-by-docker.sh
  test-server.compose.yml
  test-server.dockerfile
Labels: refactor

#47 [FIX]: DB_URL env
  .github/workflows/publish-test-server.yml
Labels: refactor

#48 [FIX]: docker-compose down applying file name
  .github/workflows/publish-test-server.yml
Labels: refactor

#54 [FIX]: Apply env to test server publishing
  .github/workflows/publish-test-server.yml
  docker-compose.yml
  run-by-docker.bat
  run-by-docker.sh
  src/main/java/com/example/ezports/global/config/SwaggerConfig.java
  src/main/resources/application.yml
  test-server.compose.yml
  test-server.dockerfile
Labels: refactor

#55 Develop
  .github/workflows/publish-test-server.yml
  src/main/java/com/example/ezports/global/config/SwaggerConfig.java
  src/main/resources/application.yml
  test-server.compose.yml
Labels: refactor

#57 [FIX]/#56-비로그인 시에도 리그/팀 페이지 조회 할 수 있도록 수정 + CORS 설정
  src/main/java/com/example/ezports/global/config/CorsConfig.java
  src/main/java/com/example/ezports/global/config/SecurityConfig.java
Labels: bug

#62 [FIX]/#59-스프링 시큐리티 엔드포인트 전체 허용
  src/main/java/com/example/ezports/global/config/SecurityConfig.java
Labels: bug
